### ISSUE TITLE
TODO:s Overview of features needed in Pkg3 

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/Pkg.jl#249]
This is a summary of the main points I think are left to do in terms of features that need to exist for Pkg3 (for now).

- [x] Finish up the compatibility #234 
- [x] OS-specific dependencies and have these be recorded in the registry. (not implemented for now)
- [x] Build / test-target dependencies. Need not to be registered in the registry. **Update**: I think we should punt on build-target deps for now.
- [ ] Port `PkgDev.tag` and `PkgDev.register` to work with the new registry format.
- [ ] Port AttoBot to work with the functions above.
- [ ] Port the consistency tests in METADATA to the Registry.
- [ ] Enable JuliaCIBot for the Registry.
- [ ] Update existing packages with Project files.
 
Note that this is a list such that if anything is missing, the Pkg3 experience will be significantly worse. It is not a "nice to have"-list.
